version: '3.8'

services:
  nksp:
    build: .
    command: python app.py
    container_name: nksp
    environment:
      - SECRET_FLASK=secret_flask
      - SECRET_JWT=secret_jwt
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPACE=dev
    ports:
      - '5000:5000'
    networks:
      - nksp_net
    depends_on:
      - redis
  redis:
    image: redis:6.0.8
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - nksp_net

networks:
  nksp_net:
    driver: bridge
